### ISSUE TITLE
Implement Discord markup to make command_guide channel easier to understand

### ISSUE THREAD

**Issue by jamesjamail** [jamesjamail/TunnelQuestBot#15]
The language is pretty verbose currently, would be nice to format user variable differently to avoid using < > as sometimes users think they need to wrap their arguments in carats.  Same thing goes with quotes for commands.

This can be duplicated to the !help command

**Comment by rm-you** [comment]
Ah, I did some of this already on the !help side, in #29 
Maybe we could just copy that out to the channel to resolve this?

**Comment by jamesjamail** [comment]
This is donezo.
