### ISSUE TITLE
Stream channel messages sometimes have some sort of ID number inserted in the message.

### ISSUE THREAD

**Issue by jamesjamail** [jamesjamail/TunnelQuestBot#20]
See attached picture.

Not sure about this one.
![TQB_bug](https://user-images.githubusercontent.com/53353772/84474612-be66f100-ac50-11ea-9191-f4c08fa54835.PNG)

**Comment by rm-you** [comment]
Yeah, I noticed that... I was theorizing it might be something to do with the way people do weird "fake item links" where it shows text for one item, but links another?
Regardless, I DOUBT it's anything we can handle, as that's basically the raw auction text. I am guessing it's that way in the logfile too.

**Comment by rm-you** [comment]
Added the `unverified` tag because we need to prove whether this issue is on our side or actually in the EQ logs.

**Comment by jamesjamail** [comment]
I don't see this happening anymore.  Shall we close it?

**Comment by rm-you** [comment]
Yeah let's have folks re-open an issue if we see it again.
