### ISSUE TITLE
Now my TunnelQuestBot only shows Blue not Green

### ISSUE THREAD

**Issue by Krowe93313** [jamesjamail/TunnelQuestBot#21]
Can you help me fix this?  Im on the green server and everything was working perfectly fine.   Now Im only seeing posts from blue server.

**Comment by rm-you** [comment]
Not sure I can replicate this -- the two channels seem to be working fine in my discord client, and are displaying different auction messages, which I can confirm at least on the Green side are coming from the correct server.

**Comment by rm-you** [comment]
User reports the issue is resolved.
