### ISSUE TITLE
Bot item link from !watches has an extra '/'

### ISSUE THREAD

**Issue by purgat0ry** [jamesjamail/TunnelQuestBot#43]
![image](https://user-images.githubusercontent.com/18694882/101171209-cc874e80-3682-11eb-8019-2f656e922514.png)
![image](https://user-images.githubusercontent.com/18694882/101171263-dad56a80-3682-11eb-9ca2-0f006a4fbcd0.png)

**Comment by jamesjamail** [comment]
Thanks so much for flagging this, Resolved.
