### ISSUE TITLE
Allow users to watch "WTB" auctions as well.

### ISSUE THREAD

**Issue by jamesjamail** [jamesjamail/TunnelQuestBot#44]
`!watch <item>, <server>, <[price]>, <[wtb]>`

-need to refactor !watch command based on above
-need to refactor logParser.js regex to validate WTB auctions
-need to refactor price conditional if WTB watch

**Comment by rm-you** [comment]
Technically we already should know if it's WTB or WTS fairly accurately:
https://github.com/jamesjamail/TunnelQuestBot/blob/master/src/utility/wikiHandler.js#L35-L36
I think the issue is that we parse for the stream and parse for the watcher as two different paths?

**Comment by rm-you** [comment]
This will be handled in the next release (typescript/prisma refactor).

**Comment by rm-you** [comment]
This has been live for a while, and appears to be working as intended.
