### ISSUE TITLE
zumaik's animation not showing up

### ISSUE THREAD

**Issue by smasherprog** [jamesjamail/TunnelQuestBot#49]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/3393733/228646280-6691abb0-3e7a-45e8-b069-d6b6fc80e859.png">

if you search you will see its in the body of the message, but not as a found item.

**Comment by smasherprog** [comment]
Is this repo maintained?

**Comment by rm-you** [comment]
Yes, it is, but we don't necessarily check the Issues page often -- report bugs in discord in the feedback channel!
As for this bug -- the author of the other issue appears to understand the problem, and this is a common one -- many items have discrepancies in their naming when they use apostrophes, between what the wiki believes and what is true in-game.
I'll look at fixing it soon.

**Comment by rm-you** [comment]
@smasherprog Should be fixed! Sorry for the delay. :)

**Comment by rm-you** [comment]
Following up, the change was merged but the new version didn't roll out properly, so we're stuck on some of these issues until the refactor is done, hopefully within a week or two.
