### ISSUE TITLE
Jade Chokidai Prod not showing correctly in tunnel stream

### ISSUE THREAD

**Issue by smasherprog** [jamesjamail/TunnelQuestBot#53]
<img width="1075" alt="image" src="https://github.com/jamesjamail/TunnelQuestBot/assets/3393733/b949a68c-f736-4b2f-bf81-d638f5300ef4">

**Comment by rm-you** [comment]
Ah, this is because the item entries are like so:
```
    "JADE CHOKIDAI PROD (NERFED)": "/Jade_Chokidai_Prod_(nerfed)",
    "JADE CHOKIDAI PROD (PRE-NERF)": "/Jade_Chokidai_Prod_(Pre-Nerf)",
```

Will be fixed in https://github.com/jamesjamail/TunnelQuestBot/tree/tsc_prisma_refactor

**Comment by rm-you** [comment]
@smasherprog thanks for reporting these! you can ping me directly on Discord for a faster response if you'd like, I only check these issues periodically. If you notice one of these, ping @devs in the feedback channel.

**Comment by rm-you** [comment]
Should have been resolved, feel free to re-open if you have another similar issue.
